### ISSUE TITLE
CheckoutTwoPage return types

### ISSUE THREAD

**Issue by ThatGuyGilby** [ThistleBlue22/SwagLabsFeudalOverlords#18]
getItemTotal, getTax and getTotal need to return double values not ints.

**Comment by ThatGuyGilby** [comment]
A number format exception is also thrown on the call of getItemTotal

```java.lang.NumberFormatException: For input string: "Item total: $0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.valueOf(Integer.java:999)
	at com.feudaloverlords.swaglabs.pom.CheckoutTwoPage.getItemTotal(CheckoutTwoPage.java:33)
	at SwagLabsCheckoutTestsMyStepdefs.theSummaryTotalShouldBeEqualToTheSummarySubtotalPlusTax(SwagLabsCheckoutTestsMyStepdefs.java:80)
	at ✽.the summary total should be equal to the summary subtotal plus tax(file:///E:/Java%20Projects/SwagLabsFeudalOverlords/src/test/resources/features/SwagLabsCheckoutTests.feature:16)

**Comment by ThatGuyGilby** [comment]
Methods fixed to work with the testing framework.
